name: erl_interface_build
inputs:
  otp_version:
    type: string
    required: true
  xcomp_conf:
    type: string
    required: true
  name:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout OTP ${{ inputs.otp_version }}
      uses: actions/checkout@v4
      with:
        repository: erlang/otp
        ref: OTP-${{ inputs.otp_version }}
        path: otp
    - name: Build
      working-directory: otp
      shell: bash
      run: |
        set -a
        source ${{ inputs.xcomp_conf }}
        set +a

        export ERL_TOP=$(pwd)
        export TARGET=$erl_xcomp_host

        ./configure --host=$erl_xcomp_host
        (cd lib/erl_interface && ./configure --host=$erl_xcomp_host)
        (cd lib/erl_interface/src && make release)

        mkdir -p ../artifacts
        cp lib/erl_interface/obj/$(erts/autoconf/config.sub $erl_xcomp_host)/libei.a ../artifacts/libei.a
    - name: Produce Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: artifacts/libei.a