name: erl_interface
on:
  push:
    tags:
      - "*.*.*"
jobs:
  ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/erl_interface_build
        with:
          otp_version: ${{ github.ref }}
          xcomp_conf: xcomp/erl-xcomp-arm64-ios.conf
          name: universal-libei-ios

  ios_simulator_split_arch:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
    name: Build iOS Simulator (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/erl_interface_build
        with:
          otp_version: ${{ github.ref }}
          xcomp_conf: xcomp/erl-xcomp-${{ matrix.arch }}-iossimulator.conf
          name: libei-iossimulator-${{ matrix.arch }}
  ios_simulator:
    name: Merge iOS Simulator Archs
    runs-on: macos-latest
    needs: [ios_simulator_split_arch]
    steps:
      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: libei-iossimulator-*
      - name: Merge Architectures
        run: lipo -create -output universal-libei-iossimulator.a$(find artifacts -type f -name '*.a' | xargs -I{} printf -- ' {}')
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-libei-iossimulator
          path: universal-libei-iossimulator.a

  xcframework:
    runs-on: macos-latest
    needs: [ios, ios_simulator]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: priv/erl_interface_include
      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: universal-libei-*
          path: artifacts
      - name: Make xcframework
        run: xcodebuild -create-xcframework -output erl_interface.xcframework $(find artifacts -type f -name '*.a' | xargs -I{} printf -- '-library %s -headers priv/erl_interface_include ' {})
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: erl_interface.xcframework
          path: erl_interface.xcframework
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: erl_interface.xcframework